version: "3.8"

services:
  loadbalancer:
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
